name: ci-workflow
on: [push]
jobs:
  check-aplication:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Node.js 20.x setup
    - uses: actions/setup-node@v4
      with:
          node-version: '20.x'

    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test